name: Publish Package to npmjs
on:
  push:
    tags: 
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checking out repository
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      # Setting .npmrc file up to publish to npm
      - name: Setting things up ğŸ”§
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # User or organization
          scope: '@dative-gpi'

      # Publishing with tag name as version
      - name: Publishing to npmjs ğŸš€
        run: |
          cd src
          yarn
          yarn version --new-version ${{ github.ref_name }} --no-git-tag-version
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}